name = "waccyy's Fantasia zh-TW"
author = "AosakiReiya"
version = "Beta11.9-A0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3131ace53a9cec52508128c6dddcfd04acce8484c5f983c3088c3c2436ad762c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
