name = "waccyy's Fantasia zh-TW"
author = "AosakiReiya"
version = "Beta11.9-A0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca6e147563c1e51d4446d43df5fe853e7109d2154db5c5418b293f435a1a701"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
