name = "waccyy's Fantasia Taiwanese Translate"
version = "Beta 11.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee1a1c412c121094d4824e16b12ad7acdefc83cc69c35f01f2e8889ab0a3c888"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
