ServerEvents.tags("item", event => {

  event.add(
    "diet:vegetables",
    [
      "culturaldelights:corn_cob",
      "mynethersdelight:plate_of_stuffed_hoglin_snout",
      "mynethersdelight:plate_of_stuffed_hoglin_ham",
      "mynethersdelight:plate_of_stuffed_hoglin",
      "culturaldelights:eggplant_parmesan",
      "sniffers_delight:sniffer_egg_soup",
      "sniffers_delight:torchflower_salad",
      "sniffers_delight:moss_salad",
      "lilis_lucky_lures:cooked_cod_meal",
      "lilis_lucky_lures:salmon_rolls",
      "lilis_lucky_lures:grilled_tropical_fish",
      "lilis_lucky_lures:puffer_plater",
      "lilis_lucky_lures:uncooked_cod_meal",
      "lilis_lucky_lures:uncooked_puffer_plater",
      "lilis_lucky_lures:uncooked_tropical_fish",
      "farmersdelight:roasted_mutton_chops",
      "farmersdelight:steak_and_potatoes",
      "farmersdelight:mixed_salad",
      "unusualfishmod:pickledish",
      "unusualfishmod:strange_broth",
      "farmersdelight:nether_salad",
      "farmersdelight:squid_ink_pasta",
      "mynethersdelight:bullet_pepper",
      "mynethersdelight:stuffed_pepper",
      "mynethersdelight:spicy_cotton",
      "mynethersdelight:spicy_skewer",
      "brewinandchewin:fiery_fondue"
    ])

  event.add(
    "diet:grains",
    [
      "culturaldelights:tortilla",
      "hearthandharvest:peanut",
      "culturaldelights:eggplant_parmesan",
      "hearthandharvest:waffle",
      "alexsmobs:mosquito_repellent_stew",
      "farmersdelight:cooked_rice",
      "farmersdelight:chocolate_pie_slice",
      "farmersdelight:chocolate_pie",
      "farmersdelight:squid_ink_pasta",
      "culturaldelights:elote",
      "brewinandchewin:fiery_fondue"
    ])

  event.add(
    "diet:fruits",
    [
      "hearthandharvest:blueberries",
      "hearthandharvest:cherry",
      "hearthandharvest:raspberry",
      "hearthandharvest:red_grapes",
      "hearthandharvest:green_grapes",
      "regions_unexplored:duskmelon_slice",
      "regions_unexplored:salmonberry",
      "regions_unexplored:hanging_earlight_fruit",
      "quark:ancient_fruit"
    ])

  event.add(
    "diet:proteins",
    [
      "mynethersdelight:enchanted_golden_egg",
      "mynethersdelight:hoglin_loin",
      "mynethersdelight:roast_ear",
      "mynethersdelight:plate_of_stuffed_hoglin_snout",
      "mynethersdelight:plate_of_stuffed_hoglin_ham",
      "mynethersdelight:plate_of_stuffed_hoglin",
      "mynethersdelight:strider_egg",
      "mynethersdelight:strider_slice",
      "mynethersdelight:minced_strider",
      "mynethersdelight:plate_of_striderloaf",
      "mynethersdelight:plate_of_cold_striderloaf",
      "mynethersdelight:ghasta",
      "mynethersdelight:plate_of_ghasta_with_cream",
      "culturaldelights:eggplant_parmesan",
      "hearthandharvest:goat_cheese_slice",
      "brewinandchewin:flaxen_cheese_wedge",
      "brewinandchewin:scarlet_cheese_wedge",
      "unusualfishmod:raw_lobster",
      "sniffers_delight:raw_sniffer_steak",
      "sniffers_delight:boiled_sniffer_egg",
      "sniffers_delight:sniffer_egg_soup",
      "lilis_lucky_lures:cooked_cod_meal",
      "lilis_lucky_lures:salmon_rolls",
      "lilis_lucky_lures:grilled_tropical_fish",
      "lilis_lucky_lures:puffer_plater",
      "lilis_lucky_lures:uncooked_cod_meal",
      "lilis_lucky_lures:uncooked_puffer_plater",
      "lilis_lucky_lures:uncooked_tropical_fish",
      "mynethersdelight:hotdog_with_mixed_salad",
      "mynethersdelight:hotdog_with_nether_salad",
      "mynethersdelight:breakfast_sampler",
      "mynethersdelight:blue_tenderloin_steak",
      "mynethersdelight:bleeding_tartar",
      "mynethersdelight:ghast_salad",
      "mynethersdelight:dried_ghast_with_milk",
      "mynethersdelight:sizzling_pudding",
      "alexsdelight:maggot_salad",
      "farmersdelight:bacon_and_eggs",
      "farmersdelight:roasted_mutton_chops",
      "farmersdelight:steak_and_potatoes",
      "incubation:scrambled_eggs",
      "unusualfishmod:strange_broth",
      "farmersdelight:squid_ink_pasta",
      "mynethersdelight:tear_popsicle",
      "mynethersdelight:stuffed_pepper",
      "mynethersdelight:spicy_cotton",
      "mynethersdelight:spicy_skewer",
      "brewinandchewin:fiery_fondue"
    ])

  event.add(
    "diet:sugars",
    [
      "hearthandharvest:waffle",
      "farmersdelight:chocolate_pie_slice",
      "farmersdelight:chocolate_pie"
    ])

  event.remove("forge:cooked_eggs", "incubation:fried_egg")
  event.remove("diet:sugars", ["brewinandchewin:flaxen_cheese_wedge", "brewinandchewin:scarlet_cheese_wedge"])

  let fruitless = [
    "incubation:scrambled_eggs",
    "hearthandharvest:waffle",
    "mynethersdelight:hotdog_with_mixed_salad",
    "mynethersdelight:hotdog_with_nether_salad",
    "mynethersdelight:breakfast_sampler",
    "mynethersdelight:blue_tenderloin_steak",
    "mynethersdelight:bleeding_tartar",
    "mynethersdelight:ghast_salad",
    "mynethersdelight:dried_ghast_with_milk",
    "mynethersdelight:sizzling_pudding",
    "unusualfishmod:pickledish",
    "unusualfishmod:strange_broth",
    "alexsmobs:mosquito_repellent_stew",
    "farmersdelight:mixed_salad",
    "farmersdelight:nether_salad",
    "farmersdelight:bacon_and_eggs",
    "farmersdelight:roasted_mutton_chops",
    "farmersdelight:steak_and_potatoes",
    "alexsdelight:maggot_salad",
    "lilis_lucky_lures:cooked_cod_meal",
    "lilis_lucky_lures:salmon_rolls",
    "lilis_lucky_lures:grilled_tropical_fish",
    "lilis_lucky_lures:puffer_plater",
    "lilis_lucky_lures:uncooked_cod_meal",
    "lilis_lucky_lures:uncooked_puffer_plater",
    "lilis_lucky_lures:uncooked_tropical_fish",
    "sniffers_delight:torchflower_salad",
    "sniffers_delight:moss_salad",
  ]
  fruitless.forEach(o => event.remove("diet:fruits", o))
})