// Fantasia 物品名稱強制覆蓋
// 直接註冊語言 key，不受 RP 或 Component.literal() 影響

ClientEvents.lang('zh_tw', event => {

    // ===== Dawn Day (epicfight_dd) =====
    event.add('item.epicfight_dd.iron_knife', '鐵匕首')
    event.add('item.epicfight_dd.iron_light_greatsword', '鐵光輝巨劍')
    event.add('item.epicfight_dd.iron_messer', '鐵大砍刀')
    event.add('item.epicfight_dd.iron_florett', '鐵輕劍')
    event.add('item.epicfight_dd.iron_halberd', '鐵長戟')
    event.add('item.epicfight_dd.iron_battlestaff', '鐵戰鬥法杖')

    event.add('item.epicfight_dd.golden_knife', '黃金匕首')
    event.add('item.epicfight_dd.golden_light_greatsword', '黃金光輝巨劍')
    event.add('item.epicfight_dd.golden_messer', '黃金大砍刀')
    event.add('item.epicfight_dd.golden_florett', '黃金輕劍')
    event.add('item.epicfight_dd.golden_halberd', '黃金長戟')
    event.add('item.epicfight_dd.golden_battlestaff', '黃金戰鬥法杖')

    event.add('item.epicfight_dd.diamond_knife', '鑽石匕首')
    event.add('item.epicfight_dd.diamond_light_greatsword', '鑽石光輝巨劍')
    event.add('item.epicfight_dd.diamond_messer', '鑽石大砍刀')
    event.add('item.epicfight_dd.diamond_florett', '鑽石輕劍')
    event.add('item.epicfight_dd.diamond_halberd', '鑽石長戟')
    event.add('item.epicfight_dd.diamond_battlestaff', '鑽石戰鬥法杖')

    event.add('item.epicfight_dd.netherite_knife', '獄髓匕首')
    event.add('item.epicfight_dd.netherite_light_greatsword', '獄髓光輝巨劍')
    event.add('item.epicfight_dd.netherite_messer', '獄髓大砍刀')
    event.add('item.epicfight_dd.netherite_florett', '獄髓輕劍')
    event.add('item.epicfight_dd.netherite_halberd', '獄髓長戟')
    event.add('item.epicfight_dd.netherite_battlestaff', '獄髓戰鬥法杖')

    event.add('item.epicfight_dd.milady', '女士')
    event.add('item.epicfight_dd.bat', '木製球棒')
    event.add('item.epicfight_dd.wooden_battlestaff', '大木棍')
    event.add('item.epicfight_dd.ruby', '紅寶石')
    event.add('item.epicfight_dd.eclipse', '日蝕')
    event.add('item.epicfight_dd.vitreus', '玻璃')
    event.add('item.epicfight_dd.saber', '軍刀')
    event.add('item.epicfight_dd.steelaxe', '鋼斧')
    event.add('item.epicfight_dd.war_sickle', '戰鐮')
    event.add('item.epicfight_dd.herb_sickle', '鐮刀')
    event.add('item.epicfight_dd.backhand_blade', '反手刀')
    event.add('item.epicfight_dd.bonecutting_saw', '骨鋸')
    event.add('item.epicfight_dd.nail', '鐵釘')
    event.add('item.epicfight_dd.nailbat', '尖刺球棒')
    event.add('item.epicfight_dd.energydrink.empty', '能量飲料')
    event.add('item.epicfight_dd.energydrink.effect.empty', '超棒能量飲料！')
    event.add('item.epicfight_dd.blood_ritus_dagger', '血儀式匕首')
    event.add('item.epicfight_dd.night_ritus_dagger', '夜儀式匕首')

    // ===== Create Missiles (createmissiles) =====
    event.add('block.createmissiles.control_panel', '控制面板')
    event.add('block.createmissiles.assembly_panel', '組裝面板')
    event.add('block.createmissiles.navigation_panel', '導航面板')
    event.add('block.createmissiles.launch_pad', '發射台')
    event.add('item.createmissiles.biome_vial', '生態域試管')
    event.add('item.createmissiles.dragon_egg_shell', '龍蛋殼')
    event.add('item.createmissiles.reinforced_dragon_egg_shell', '強化龍蛋殼')
    event.add('item.createmissiles.bound_ender_pearl', '綁定終界珍珠')
    event.add('item.createmissiles.basic_drone_box', '基本無人機盒')
    event.add('item.createmissiles.reinforced_drone_box', '強化無人機盒')
    event.add('item.createmissiles.incomplete_basic_drone_box', '未完成的基本無人機盒')
    event.add('item.createmissiles.incomplete_reinforced_drone_box', '未完成的強化無人機盒')
    event.add('item.createmissiles.excavator_upgrade_core', '挖掘升級核心')
    event.add('item.createmissiles.firework_upgrade_core', '煙火升級核心')
    event.add('item.createmissiles.flaming_upgrade_core', '火焰升級核心')
    event.add('item.createmissiles.frost_upgrade_core', '霜凍升級核心')
    event.add('block.createmissiles.annoying_jukebox', '騷擾點唱機')
    event.add('block.createmissiles.frost_snow', '冰霜雪')
    event.add('block.createmissiles.infernal_ash', '地獄灰燼')
    event.add('item.createmissiles.chassis_assembly', '機身組裝')
    event.add('item.createmissiles.thruster_assembly', '推進器組裝')
    event.add('item.createmissiles.warhead_assembly', '彈頭組裝')

    // ===== Valley Sky (valleysky) =====
    event.add('block.valleysky.elm_planks', '榆木材')
    event.add('block.valleysky.gracefelt_planks', '恩惠木材')
    event.add('block.valleysky.haligrot_block', '聖窟')
    event.add('block.valleysky.haligtree_planks', '聖樹木材')
    event.add('block.valleysky.roundtable', '圓桌')
    event.add('block.valleysky.site_of_grace', '賜福')
    event.add('block.valleysky.study_table', '書桌')
    event.add('block.valleysky.totem_bed', '圖騰床')
    event.add('creativetab.main_tab', '山谷與天空')
    event.add('effect.valleysky.bleed.max_level', '你正在大量失血！')
    event.add('effect.valleysky.texture_swap', '幻滅')
    event.add('entity.valleysky.fc', '手指苦力怕')
    event.add('entity.valleysky.lobster', '龍蝦')
    event.add('entity.valleysky.tortoise', '陸龜')
    event.add('entity.valleysky.warhawk', '戰鷹')
    event.add('item.valleysky.glintstone_scrap', '輝石碎片')
    event.add('item.valleysky.metaball', '變形球')
    event.add('item.valleysky.vagabond_boots', '流浪者靴子')
    event.add('key.category.valleysky', '山谷與天空')
})
