#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 23 19:26:01 HKT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=ComplementaryUnbound_r5.8.1.zip
enableShaders=true
