#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 29 07:42:57 HKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=9
shaderPack=Eclipse-Shader-Unstable.zip
